MoToolsMVC/Controllers/MenuController.cs
using MoToolsMVC.BLL;
using MoToolsMVC.BLL.Menu;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MoToolsMVC.Helpers;
using MoToolsMVC.Session;
using MoToolsMVC.ViewModel;

namespace MoToolsMVC.Controllers
{
    public class MenuController : Controller
    {
        private IServiceUnitOfWork _serviceUnitOfWork;

        public MenuController(IServiceUnitOfWork serviceUnitOfWork)
        {
            this._serviceUnitOfWork = serviceUnitOfWork;
        }

        [HttpGet]
        public ActionResult Get(string username)
        {
            string menuTree = Helper.Session.GetSession<string>(SessionNames.MenuTree);
            bool? isMenuOpen = Helper.Session.GetSession<bool?>(SessionNames.isMenuOpen);
            MenuViewModel menuVM = new MenuViewModel(menuTree, isMenuOpen);
            if (menuTree == null)
            {
                menuTree = _serviceUnitOfWork.MenuService.GetMenuByUser(username, HttpContext.Request.ApplicationPath.ToString());
                Helper.Session.SetSession(SessionNames.MenuTree, menuTree);                
                menuVM.MenuTree = menuTree;
                menuVM.isMenuOpen = isMenuOpen == true ? isMenuOpen : false;
            }
            return PartialView("_Menu", menuVM);
        }

        [HttpPost]
        public void SetMenuCookie(bool isMenuOpen)
        {
            //bool isMenuCollapsed = Helper.Session.GetSession<bool>(SessionNames.IsMenuCollapsed);
            Helper.Session.SetSession(SessionNames.isMenuOpen, isMenuOpen);
        }

        protected override void Dispose(bool disposing)
        {
            _serviceUnitOfWork.Dispose();
            base.Dispose(disposing);
        }

    }

}

MoToolsMVC/Controllers/TeamController.cs
//using Microsoft.WindowsAzure.Storage;
//using Microsoft.WindowsAzure.Storage.Blob;
using MoToolsMVC.BLL;
using MoToolsMVC.BLL.CaseDDLOptions;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MoToolsMVC.Controllers
{
    public class TeamController : Controller
    {
        private IServiceUnitOfWork _serviceUnitOfWork;

        //TODO: DEV
        //Get RequestId and ActivityId and AttachmentType
        public int BDTeamId { get { return 515; } }
        public Guid requestID { get { return new Guid("bf30c6b5-b97b-4adb-959b-f8f3d12b58d8"); } }
        public Guid? activityID { get { return new Guid("d6a257e6-b8fe-40b6-82d8-e0546656bd37"); } }
        public string username { get { return "boanateladmin"; } }

        public TeamController(IServiceUnitOfWork serviceUnitOfWork)
        {
            this._serviceUnitOfWork = serviceUnitOfWork;
        }

        public ActionResult GetUploadAttachmentTypes()
        {
            List<CaseDDLOption> list = _serviceUnitOfWork.AttachmentsService.GetUploadAttachmentTypes(BDTeamId);
            list = list.OrderBy(o => o.Text).ToList();
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SaveAttachment()
        {
            // Check Web.config <location path="Team/SaveAttachment"> for the maximum request length

            string attachmentName, selectedAttachmentType = Request.Form["AttachmentTypes.SelectedOption"];
            Guid tempGuid;
            Guid? attachmentType = null;
            if (Guid.TryParse(selectedAttachmentType, out tempGuid))
            {
                attachmentType = tempGuid;
            }

            try
            {
                for (int i = 0; i < Request.Files.Count; i++)
                {
                    HttpPostedFileBase file = Request.Files[i];
                    attachmentName = file.FileName;
                    var url = _serviceUnitOfWork.AttachmentsService.UploadToAzure(file.InputStream, attachmentName, requestID);
                    _serviceUnitOfWork.AttachmentsService.SaveAttachmentToBD(url, requestID, activityID, attachmentName, username, attachmentType);
                }
            }
            catch (Exception)
            {
                return Json("Error uploading");
            }

            return Json("Uploaded successfully");
        }

        public ActionResult DeleteAttachment(Guid id)
        {
            //TODO: Delete attachment
            throw new NotImplementedException();
        }

        protected override void Dispose(bool disposing)
        {
            _serviceUnitOfWork.Dispose();
            base.Dispose(disposing);
        }

    }

}

MoToolsMVC/Controllers/UserController.cs
using MoToolsMVC.BLL;
using MoToolsMVC.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MoToolsMVC.Controllers
{
    public class UserController : Controller
    {
        private IServiceUnitOfWork _serviceUnitOfWork;
        public UserController(IServiceUnitOfWork serviceUnitOfWork)
        {
            this._serviceUnitOfWork = serviceUnitOfWork;
        }

        [HttpGet]
        public ActionResult Edit(string username)
        {
            UsersRCA user = _serviceUnitOfWork.UserService.GetUser(username);
            return View(user);
        }

        protected override void Dispose(bool disposing)
        {
            _serviceUnitOfWork.Dispose();
            base.Dispose(disposing);
        }
    }
}

MoToolsMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/Vendors")
    @Styles.Render("~/CSS/MoTools")
    @Scripts.Render("~/bundles/Vendors")
    @Scripts.Render("~/bundles/Helpers")
    @RenderSection("scripts", required: false)
</head>
<body class="fullWidth fullHeight">
    <div id="tablePageLayout" class="body-table">
        <div class="main-page-contax-colors"></div>
        <div class="topBar">
            <a href="@Url.Action("Index","Home")">
                <div class="logotipo-area" onclick="location.href='/Default.aspx';"></div>
            </a>
            <div class="username-area valign-middle" style="display: table;">
                <div id="DIV_Search" class="inline" style="float:left;height: 46px;line-height: 46px;">
                    <div onkeypress="javascript:return WebForm_FireDefaultButton(event, 'Btn_Search')">
                        <input name="ctl00$TB_Search2" type="text" id="ctl00_TB_Search2" class="input-search capitalize" placeholder="Procurar Caso" autocomplete="off">
                        <input type="submit" name="ctl00$Btn_Search" value="" id="Btn_Search">
                    </div>
                </div>
                <div class="user-container inline" style="float:left;">
                    <div class="user-avatar" style="float:left; display: none"></div>
                    <div class="user-info" style="float:left;">
                        <div class="user-name">
                            <span id="ctl00_menuName">Boanateladmin</span>
                        </div>
                        <div class="user-job">
                            <span id="ctl00_menuPerfil">Manutenção</span>
                        </div>
                    </div>
                    <div class="user-open-menu" style="float:left;"></div>
                </div>
                <div class="logout-area" style="float:left; height: 46px;">
                    <input type="submit" name="ctl00$decoyEnterBtn" value="" onclick="return false;" id="ctl00_decoyEnterBtn" style="display: none;">
                    <input type="image" name="ctl00$LogOffBtn" id="ctl00_LogOffBtn" src="../img/logoutV2.png" style="height:30px;width:30px;border-width:0px;" value="">
                </div>
                <span id="ctl00_lblUsername" class="lbl-username" style="display: none">BOANATELADMIN</span>
            </div>
            <div class="user-menu">
                <ul class="user-popup">
                    <li class="greyBackground">
                        <span class="inline">
                            <span class="bold">TMT:</span>
                            00:00:00
                        </span>
                        <span class="inline">
                            <span class="bold">TRATADOS:</span>
                            0
                        </span>
                    </li>
                    <li class="config">
                        <span>Config</span>
                    </li>
                    <li class="links inline">
                        <span class="ui-icon motools-icon ui-icon-gear"></span>
                        <span>@Html.ActionLink("Editar", "Edit", "User", new { username = "joaoestrela" }, null)</span>
                    </li>
                </ul>
            </div>
        </div>
        <table border="0" cellpadding="0" cellspacing="0" class="body-table">
            <tbody>
                <tr>
                    @{Html.RenderAction("Get", "Menu");}
                    <td class="default-background" align="left" valign="top">
                        <div class="white-background"></div>
                        <div ID="MasterPanel" class="fullWidth scrollableX scrollableY"  style="min-height: 800px">
                            @RenderBody()
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    @*@Html.Action("Render", "Menu", User.Identity.Name)*@
    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
    @Scripts.Render("~/bundles/Main")
</body>
</html>

MoToolsMVC/Views/Shared/_LayoutOriginal.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MoToolsMVC/Views/Shared/_Menu.cshtml
@model MoToolsMVC.ViewModel.MenuViewModel

@Styles.Render("~/CSS/SideMenu")
<td id="TD_MenuArea" class="menu-area @(@Model.isMenuOpen == true ? "" : "menu-vertical")" style="width: 36px;">
    <div id="lineGlowDiv">
        &nbsp;
    </div>
    <div id="menu-hamburger" class="menu-hamburger">
        <div id="goToHome" >

            <img id="homeButton" src="../img/home.png" alt="Home" style="border-width:0px;">
            <span id="goToHomeText" >HOME</span>

        </div>
        <div>
            <img alt="Hamburger" id="IMG_Hamburger_Menu" src="../img/MenuIcon.png" data-src="@Url.Action("SetMenuCookie", "Menu")">
        </div>
    </div>
    <div id="menuLabel" class="container-Menu-Label">
        <span class="MenuClass">Menu</span>
    </div>
    <div id="menuInitialContent" class="menu-width @(@Model.isMenuOpen == true ? "" : "displayNone")">
        <div id="menuTree">
            @Html.Raw(Model.MenuTree)
        </div>
    </div>
</td>

@Scripts.Render("~/bundles/Menu")

MoToolsMVC/Views/Shared/_Upload.cshtml
@model MoToolsMVC.ViewModel.UploadModel

@* ---------------------------------------------------------------------------------------------------------------------------------------------------- *@

<div id="ctl00_Content1_Panel1" class="divBegining" style="background-color:#E5E9EC;border-width:0px;width:98%;">
    <fieldset style="border-width: 0;">
        <br>
        <div id="ctl00_Content1_PanelDatatable" class="divBegining fullWidth whiteBackground">

            @* ---------------------------------------------------------------------------------------------------------------------------------------------------- *@

            @Styles.Render("~/CSS/Upload")

            <div class="upload-container">
                <div class="blockContainer">
                    <div class="caseTitleContainer">
                        <div class="caseTitle"><strong>Arquivos</strong></div>
                    </div>

                    <div class="labelInputContainer fullWidth">
                        <button class="attachment-popup-open">@Html.Raw(Model.UploadButtonName)</button>

                        <div class="upload-popup" style="display: none; font-size: 10px;">
                            <div class="alertify-cover"></div>
                            <div class="alertify alertify-confirm" style="top: 10%;">
                                <div class="alertify-dialog">
                                    @using (Html.BeginForm("SaveAttachment", "Team", FormMethod.Post, new { enctype = "multipart/form-data", @class = "attachment-form" }))
                                    {
                                        <div class="alertify-inner">
                                            <p class="alertify-title">Arquivos</p>
                                            <div class="alertify-message">

                                                <div class="attachment-type-container alertify-message">
                                                    <label for="attachment-type">Tipo</label>
                                                    @Html.DropDownListFor(m => m.AttachmentTypes.SelectedOption, Model.AttachmentTypes.Options, new { @class = "attachment-type", @name = "attachment-type" })
                                                </div>

                                                <div class="attachment-file-form">
                                                    <input type="file" name="file" class="attachment-file" />
                                                </div>

                                            </div>

                                            <div class="alertify-buttons">
                                                <input type="submit" value="Cancelar" class="alertify-button alertify-button-cancel close-popup" title="Cancelar">
                                                <input type="submit" value="Salvar" class="alertify-button alertify-button-ok save-attachment" title="Salvar Anexo">
                                            </div>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="attachments-list-container">
                    <span>Arquivos da atividade</span>
                    <div class="attachments-list">
                        <div class="emptyDataText">Sem arquivos</div>
                    </div>
                </div>
            </div>

            @Scripts.Render("~/bundles/Upload")

            @* ---------------------------------------------------------------------------------------------------------------------------------------------------- *@

        </div>
    </fieldset>
</div>